import { View, Text } from "react-native";

export default function Report() {
  return (
    <View style={{ padding: 20 }}>
      <Text>
        Rx/Check Report
      </Text>

      <Text>
        Risk Score: 82
      </Text>

      <Text>
        LOW RISK
      </Text>

      <Text>
        Generated by Rx/Check AI
      </Text>
    </View>
  );
}
